In [1]:
import numpy as np # linear algebra
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
import keras
import tensorflow as tf

C:\Users\Pinocchio\AppData\Local\Temp\ipykernel_10536\1372223488.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
df = pd.read_csv('QAs_Category_SubCategory_Servicenow.csv')
df.head()

Category Subcategory  \
0  Inquiry/Help   Antivirus   
1  Inquiry/Help   Antivirus   
2  Inquiry/Help   Antivirus   
3  Inquiry/Help   Antivirus   
4  Inquiry/Help   Antivirus   

                                            Question  \
0  How to update the antivirus definition files m...   
1  What to do if the antivirus scan is taking too...   
2  How to troubleshoot if the antivirus is blocki...   
3  What steps to take if the antivirus is not upd...   
4  How to perform a manual antivirus scan on a sp...   

                                              Answer  
0  To manually update antivirus definition files,...  
1  If the antivirus scan is prolonged, check syst...  
2  If the antivirus is blocking a legitimate appl...  
3  If the antivirus fails to update automatically...  
4  To manually scan a specific folder or file, op...

In [3]:
df.drop(['Answer','Subcategory'], axis=1, inplace=True)
df

Category                                           Question
0    Inquiry/Help  How to update the antivirus definition files m...
1    Inquiry/Help  What to do if the antivirus scan is taking too...
2    Inquiry/Help  How to troubleshoot if the antivirus is blocki...
3    Inquiry/Help  What steps to take if the antivirus is not upd...
4    Inquiry/Help  How to perform a manual antivirus scan on a sp...
..            ...                                                ...
185       Network  What steps to take if there are deadlock issue...
186       Network  How to resolve issues with Oracle database ins...
187       Network  What to do if there are errors during Oracle d...
188       Network  How to troubleshoot issues with missing or cor...
189       Network  What steps to take if there are problems with ...

[190 rows x 2 columns]

In [4]:
df['Category'].value_counts()

Category
Hardware        60
Network         60
Inquiry/Help    30
Software        20
Database        20
Name: count, dtype: int64

In [5]:
df.info

<bound method DataFrame.info of          Category                                           Question
0    Inquiry/Help  How to update the antivirus definition files m...
1    Inquiry/Help  What to do if the antivirus scan is taking too...
2    Inquiry/Help  How to troubleshoot if the antivirus is blocki...
3    Inquiry/Help  What steps to take if the antivirus is not upd...
4    Inquiry/Help  How to perform a manual antivirus scan on a sp...
..            ...                                                ...
185       Network  What steps to take if there are deadlock issue...
186       Network  How to resolve issues with Oracle database ins...
187       Network  What to do if there are errors during Oracle d...
188       Network  How to troubleshoot issues with missing or cor...
189       Network  What steps to take if there are problems with ...

[190 rows x 2 columns]>

In [6]:
Category_n = LabelEncoder()
df['Category_n'] = Category_n.fit_transform(df['Category'])
df

Category                                           Question  \
0    Inquiry/Help  How to update the antivirus definition files m...   
1    Inquiry/Help  What to do if the antivirus scan is taking too...   
2    Inquiry/Help  How to troubleshoot if the antivirus is blocki...   
3    Inquiry/Help  What steps to take if the antivirus is not upd...   
4    Inquiry/Help  How to perform a manual antivirus scan on a sp...   
..            ...                                                ...   
185       Network  What steps to take if there are deadlock issue...   
186       Network  How to resolve issues with Oracle database ins...   
187       Network  What to do if there are errors during Oracle d...   
188       Network  How to troubleshoot issues with missing or cor...   
189       Network  What steps to take if there are problems with ...   

     Category_n  
0             2  
1             2  
2             2  
3             2  
4             2  
..          ...  
185           3  
186           3  
187           3  
188           3  
189           3  

[190 rows x 3 columns]

In [7]:
df['Category_n'].value_counts()

Category_n
1    60
3    60
2    30
4    20
0    20
Name: count, dtype: int64

In [8]:
x = df['Question']
y = df['Category_n']
y = y.to_numpy()

In [9]:
x

0      How to update the antivirus definition files m...
1      What to do if the antivirus scan is taking too...
2      How to troubleshoot if the antivirus is blocki...
3      What steps to take if the antivirus is not upd...
4      How to perform a manual antivirus scan on a sp...
                             ...                        
185    What steps to take if there are deadlock issue...
186    How to resolve issues with Oracle database ins...
187    What to do if there are errors during Oracle d...
188    How to troubleshoot issues with missing or cor...
189    What steps to take if there are problems with ...
Name: Question, Length: 190, dtype: object

In [10]:
y

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2)

In [12]:
x_train.shape , y_train.shape, x_test.shape, y_test.shape

((152,), (152,), (38,), (38,))

In [13]:
max_words = 1100
max_len = 200



tok = Tokenizer(num_words=max_words) 
tok.fit_on_texts(x_train)            
seq = tok.texts_to_sequences(x_train) 
seq_matrix = sequence.pad_sequences(sequences=seq, maxlen=max_len)   

seq_matrix

array([[  0,   0,   0, ...,  58,  34,  26],
       [  0,   0,   0, ...,  13,   2,  30],
       [  0,   0,   0, ...,  16,   2,  36],
       ...,
       [  0,   0,   0, ...,  13,   2,  25],
       [  0,   0,   0, ..., 303,  18,  77],
       [  0,   0,   0, ...,  13,   2,  30]])

In [14]:
test_seq = tok.texts_to_sequences(x_test)
test_seq_matrix = sequence.pad_sequences(test_seq, maxlen=max_len)

test_seq_matrix

array([[  0,   0,   0, ...,   2,  44, 110],
       [  0,   0,   0, ...,  40,  19,  62],
       [  0,   0,   0, ...,   2,  52, 252],
       ...,
       [  0,   0,   0, ...,  16,   2,  36],
       [  0,   0,   0, ...,  50,  51,  53],
       [  0,   0,   0, ...,   2,  28,  25]])

In [15]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=max_words, output_dim=6, input_length=max_len))
model.add(tf.keras.layers.LSTM(64, activation='tanh'))
model.add(tf.keras.layers.Dense(220, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(6, activation='softmax'))  # 6 units for classification

model.compile(optimizer=tf.keras.optimizers.AdamW(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(seq_matrix, y_train, batch_size=2, epochs=100, validation_split=0.2)


Epoch 1/100


61/61 [==============================] - 7s 68ms/step - loss: 1.7044 - accuracy: 0.2231 - val_loss: 1.5514 - val_accuracy: 0.1935
Epoch 2/100
61/61 [==============================] - 3s 57ms/step - loss: 1.5713 - accuracy: 0.3471 - val_loss: 1.5743 - val_accuracy: 0.1935
Epoch 3/100
61/61 [==============================] - 4s 58ms/step - loss: 1.5588 - accuracy: 0.3140 - val_loss: 1.5554 - val_accuracy: 0.1935
Epoch 4/100
61/61 [==============================] - 4s 61ms/step - loss: 1.5170 - accuracy: 0.3058 - val_loss: 1.4919 - val_accuracy: 0.1935
Epoch 5/100
61/61 [==============================] - 3s 57ms/step - loss: 1.4100 - accuracy: 0.3306 - val_loss: 1.3620 - val_accuracy: 0.4194
Epoch 6/100
61/61 [==============================] - 4s 58ms/step - loss: 1.2185 - accuracy: 0.5950 - val_loss: 1.2533 - val_accuracy: 0.4516
Epoch 7/100
61/61 [==============================] - 4s 58ms/step - loss: 0.7816 - accuracy: 0.7107 - val_loss: 0.8214 - val_accuracy: 0.5806
Epoc

In [19]:
model.save('./Question_category_classification.h5')
print("Model saved successfully!")

loaded_model = tf.keras.models.load_model('./Question_category_classification.h5')
print("Model loaded successfully!")

Model saved successfully!
Model loaded successfully!


In [20]:
integer_mapping = {l:i for i,l in enumerate(Category_n.classes_)}
integer_mapping

{'Database': 0, 'Hardware': 1, 'Inquiry/Help': 2, 'Network': 3, 'Software': 4}

In [22]:
sample_questions = pd.Series(["How to resolve problems with insufficient storage space in the SQL Server database?"])



print(sample_questions[0])
sample_seq = tok.texts_to_sequences(sample_questions)
sample_seq_matrix = sequence.pad_sequences(sample_seq, maxlen=max_len)
print(sample_seq_matrix.shape)
sample_intent = loaded_model.predict(sample_seq_matrix)
print(sample_intent)

sample_intent_type = [k.argmax() for k in sample_intent]

sample_intent_type



How to resolve problems with insufficient storage space in the SQL Server database?
(1, 200)
1/1 [==============================] - 0s 37ms/step
[[9.9993634e-01 1.0015471e-07 4.6863720e-06 9.5906762e-06 4.9389244e-05
  5.0341362e-09]]


[0]