In [2]:
import numpy as np # linear algebra
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
import keras
import tensorflow as tf

C:\Users\Pinocchio\AppData\Local\Temp\ipykernel_16928\1372223488.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
df = pd.read_csv('QAs_Category_SubCategory_Servicenow.csv')
df.head()

Category Subcategory  \
0  Inquiry/Help   Antivirus   
1  Inquiry/Help   Antivirus   
2  Inquiry/Help   Antivirus   
3  Inquiry/Help   Antivirus   
4  Inquiry/Help   Antivirus   

                                            Question  \
0  How to update the antivirus definition files m...   
1  What to do if the antivirus scan is taking too...   
2  How to troubleshoot if the antivirus is blocki...   
3  What steps to take if the antivirus is not upd...   
4  How to perform a manual antivirus scan on a sp...   

                                              Answer  
0  To manually update antivirus definition files,...  
1  If the antivirus scan is prolonged, check syst...  
2  If the antivirus is blocking a legitimate appl...  
3  If the antivirus fails to update automatically...  
4  To manually scan a specific folder or file, op...

In [4]:
df.drop(['Answer','Category'], axis=1, inplace=True)
df

Subcategory                                           Question
0     Antivirus  How to update the antivirus definition files m...
1     Antivirus  What to do if the antivirus scan is taking too...
2     Antivirus  How to troubleshoot if the antivirus is blocki...
3     Antivirus  What steps to take if the antivirus is not upd...
4     Antivirus  How to perform a manual antivirus scan on a sp...
..          ...                                                ...
185      Oracle  What steps to take if there are deadlock issue...
186      Oracle  How to resolve issues with Oracle database ins...
187      Oracle  What to do if there are errors during Oracle d...
188      Oracle  How to troubleshoot issues with missing or cor...
189      Oracle  What steps to take if there are problems with ...

[190 rows x 2 columns]

In [5]:
df['Subcategory'].value_counts()

Subcategory
Email                   20
Antivirus               10
VPN                     10
IP Address              10
DNS                     10
MS SQL Server           10
DB2                     10
Wireless                10
DHCP                    10
Mouse                   10
Monitor                 10
Memory                  10
Keyboard                10
Disk                    10
CPU                     10
Operating System        10
Internal Application    10
Oracle                  10
Name: count, dtype: int64

In [6]:
df.info

<bound method DataFrame.info of     Subcategory                                           Question
0     Antivirus  How to update the antivirus definition files m...
1     Antivirus  What to do if the antivirus scan is taking too...
2     Antivirus  How to troubleshoot if the antivirus is blocki...
3     Antivirus  What steps to take if the antivirus is not upd...
4     Antivirus  How to perform a manual antivirus scan on a sp...
..          ...                                                ...
185      Oracle  What steps to take if there are deadlock issue...
186      Oracle  How to resolve issues with Oracle database ins...
187      Oracle  What to do if there are errors during Oracle d...
188      Oracle  How to troubleshoot issues with missing or cor...
189      Oracle  What steps to take if there are problems with ...

[190 rows x 2 columns]>

In [7]:
Subcategory_n = LabelEncoder()
df['Subcategory_n'] = Subcategory_n.fit_transform(df['Subcategory'])
df

Subcategory                                           Question  \
0     Antivirus  How to update the antivirus definition files m...   
1     Antivirus  What to do if the antivirus scan is taking too...   
2     Antivirus  How to troubleshoot if the antivirus is blocki...   
3     Antivirus  What steps to take if the antivirus is not upd...   
4     Antivirus  How to perform a manual antivirus scan on a sp...   
..          ...                                                ...   
185      Oracle  What steps to take if there are deadlock issue...   
186      Oracle  How to resolve issues with Oracle database ins...   
187      Oracle  What to do if there are errors during Oracle d...   
188      Oracle  How to troubleshoot issues with missing or cor...   
189      Oracle  What steps to take if there are problems with ...   

     Subcategory_n  
0                0  
1                0  
2                0  
3                0  
4                0  
..             ...  
185             15  
186             15  
187             15  
188             15  
189             15  

[190 rows x 3 columns]

In [8]:
df['Subcategory_n'].value_counts()

Subcategory_n
6     20
0     10
16    10
7     10
4     10
10    10
2     10
17    10
3     10
13    10
12    10
11    10
9     10
5     10
1     10
14    10
8     10
15    10
Name: count, dtype: int64

In [9]:
x = df['Question']
y = df['Subcategory_n']
y = y.to_numpy()

In [10]:
x

0      How to update the antivirus definition files m...
1      What to do if the antivirus scan is taking too...
2      How to troubleshoot if the antivirus is blocki...
3      What steps to take if the antivirus is not upd...
4      How to perform a manual antivirus scan on a sp...
                             ...                        
185    What steps to take if there are deadlock issue...
186    How to resolve issues with Oracle database ins...
187    What to do if there are errors during Oracle d...
188    How to troubleshoot issues with missing or cor...
189    What steps to take if there are problems with ...
Name: Question, Length: 190, dtype: object

In [11]:
y

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13,
       13, 13, 13, 13, 13, 13, 13, 13,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 15, 15, 15, 15, 15, 15, 15,
       15, 15, 15])

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2)

In [13]:
x_train.shape , y_train.shape, x_test.shape, y_test.shape

((152,), (152,), (38,), (38,))

In [14]:
max_words = 1100
max_len = 200



tok = Tokenizer(num_words=max_words) 
tok.fit_on_texts(x_train)            
seq = tok.texts_to_sequences(x_train) 
seq_matrix = sequence.pad_sequences(sequences=seq, maxlen=max_len)   

seq_matrix

array([[  0,   0,   0, ...,  92,  93,  22],
       [  0,   0,   0, ...,   2,  34,  31],
       [  0,   0,   0, ...,   2,  27,  28],
       ...,
       [  0,   0,   0, ...,   2, 300,  73],
       [  0,   0,   0, ..., 142,  61, 301],
       [  0,   0,   0, ...,  18,   2,  28]])

In [15]:
test_seq = tok.texts_to_sequences(x_test)
test_seq_matrix = sequence.pad_sequences(test_seq, maxlen=max_len)

test_seq_matrix

array([[  0,   0,   0, ...,   2,  44,  23],
       [  0,   0,   0, ...,  13,   2,  26],
       [  0,   0,   0, ...,   2,  53,  17],
       ...,
       [  0,   0,   0, ...,   6,   7,  63],
       [  0,   0,   0, ...,  13,   2,  69],
       [  0,   0,   0, ...,  74,  26, 273]])

In [17]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=max_words, output_dim=18, input_length=max_len))
model.add(tf.keras.layers.LSTM(64, activation='tanh'))
model.add(tf.keras.layers.Dense(220, activation='relu'))
model.add(tf.keras.layers.Dropout(0.5))
model.add(tf.keras.layers.Dense(18, activation='softmax'))  # 6 units for classification

model.compile(optimizer=tf.keras.optimizers.AdamW(), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(seq_matrix, y_train, batch_size=2, epochs=100, validation_split=0.2)


Epoch 1/100
61/61 [==============================] - 8s 78ms/step - loss: 2.8939 - accuracy: 0.0496 - val_loss: 2.8930 - val_accuracy: 0.1290
Epoch 2/100
61/61 [==============================] - 4s 60ms/step - loss: 2.8760 - accuracy: 0.1157 - val_loss: 2.8926 - val_accuracy: 0.1290
Epoch 3/100
61/61 [==============================] - 4s 58ms/step - loss: 2.8168 - accuracy: 0.1322 - val_loss: 2.8308 - val_accuracy: 0.0968
Epoch 4/100
61/61 [==============================] - 4s 58ms/step - loss: 2.6307 - accuracy: 0.1818 - val_loss: 2.6723 - val_accuracy: 0.0968
Epoch 5/100
61/61 [==============================] - 3s 57ms/step - loss: 2.6225 - accuracy: 0.2397 - val_loss: 2.5019 - val_accuracy: 0.1613
Epoch 6/100
61/61 [==============================] - 4s 61ms/step - loss: 1.9946 - accuracy: 0.3388 - val_loss: 2.4388 - val_accuracy: 0.1290
Epoch 7/100
61/61 [==============================] - 4s 58ms/step - loss: 1.6463 - accuracy: 0.4463 - val_loss: 2.1306 - val_accuracy: 0.2903
Epoch 

In [19]:
model.save('./Question_subcategory_classification.h5')
print("Model saved successfully!")

loaded_model = tf.keras.models.load_model('./Question_subcategory_classification.h5')
print("Model loaded successfully!")

Model saved successfully!
Model loaded successfully!


In [21]:
integer_mapping = {l:i for i,l in enumerate(Subcategory_n.classes_)}
integer_mapping

{'Antivirus': 0,
 'CPU': 1,
 'DB2': 2,
 'DHCP': 3,
 'DNS': 4,
 'Disk': 5,
 'Email': 6,
 'IP Address': 7,
 'Internal Application': 8,
 'Keyboard': 9,
 'MS SQL Server': 10,
 'Memory': 11,
 'Monitor': 12,
 'Mouse': 13,
 'Operating System': 14,
 'Oracle': 15,
 'VPN': 16,
 'Wireless': 17}

In [29]:
sample_questions = pd.Series(["How to resolve problems with insufficient storage space in the SQL Server database?"])



print(sample_questions[0])
sample_seq = tok.texts_to_sequences(sample_questions)
sample_seq_matrix = sequence.pad_sequences(sample_seq, maxlen=max_len)
print(sample_seq_matrix.shape)
sample_intent = loaded_model.predict(sample_seq_matrix)
print(sample_intent)

sample_intent_type = [k.argmax() for k in sample_intent]

sample_intent_type



How to resolve problems with insufficient storage space in the SQL Server database?
(1, 200)
1/1 [==============================] - 0s 40ms/step
[[1.2970958e-13 8.2140783e-14 3.4563177e-06 1.2011316e-15 5.0213973e-14
  1.9101203e-14 1.4304077e-13 3.8460662e-15 3.1869309e-11 1.1323036e-06
  9.9977988e-01 2.0983634e-12 2.1184084e-13 3.6279166e-09 1.9266848e-09
  2.0815311e-04 7.4441868e-06 2.6327499e-10]]


[10]